name: Claude Code
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Prepare Environment
        run: |
          curl -fsSL https://bun.sh/install | bash
          mkdir -p $HOME/.claude-code-router
          cat << 'EOF' > $HOME/.claude-code-router/config.json
          {
            "log": true,
            "NON_INTERACTIVE_MODE": true,
            "API_TIMEOUT_MS": 600000,
            "Providers": [
              {
                "name": "openai",
                "api_base_url": "https://text.pollinations.ai/openai",
                "api_key": "${{ secrets.OPENAI_API_KEY }}",
                "models": ["deepseek"]
              }
            ],
            "Router": {
              "default": "openai,deepseek"
            }
          }
          EOF
        shell: bash
      
      - name: Start Claude Code Router
        run: |
          echo "Starting router..."
          nohup ~/.bun/bin/bunx @musistudio/claude-code-router@latest start > /tmp/router.log 2>&1 &
          ROUTER_PID=$!
          echo "Router PID: $ROUTER_PID"
          
          echo "Waiting for router to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3456/health > /dev/null 2>&1; then
              echo "✅ Router is ready!"
              echo "Router logs:"
              cat /tmp/router.log
              break
            fi
            if [ $i -eq 30 ]; then
              echo "❌ Router failed to start within 30 seconds"
              echo "Router logs:"
              cat /tmp/router.log
              echo "Router process status:"
              ps aux | grep -i router || echo "No router process found"
              exit 1
            fi
            echo "Attempt $i/30: Router not ready yet, waiting..."
            sleep 1
          done
          
          if ! kill -0 $ROUTER_PID 2>/dev/null; then
            echo "❌ Router process died"
            echo "Router logs:"
            cat /tmp/router.log
            exit 1
          fi
          
          echo "Router is running with PID: $ROUTER_PID"
          echo "Testing router endpoint..."
          curl -v http://localhost:3456/v1/messages -H "Content-Type: application/json" -d '{"model":"deepseek","messages":[{"role":"user","content":"test"}],"max_tokens":10}' 2>&1 || echo "Test request failed"
        shell: bash
      
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        env:
          ANTHROPIC_BASE_URL: http://localhost:3456
        with:
          anthropic_api_key: "any-string-is-ok"
          
          additional_permissions: |
            actions: read
          
          custom_instructions: |
            When you complete all tasks:
            1. Update the GitHub comment ONE TIME with all completed tasks marked as [x]
            2. After receiving a successful response, respond with plain text only (no more tool calls)
            3. Your plain text response should confirm the work is complete
            
            Do not call the same tool multiple times with identical input.
            After a successful comment update with all tasks complete, respond with text only to signal completion.
